#Developer: Félix Francisco
Import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class espelhos extends javax.swing.JFrame {
     float f;
 float p;
 float y;
    
    /**
     * Creates new form espelhos
     */
    public espelhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoAlt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campofoco = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        campodist = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        botaolimpar = new javax.swing.JButton();
        botaocalcular = new javax.swing.JButton();
        campotitulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculo espelhos esféricos");
        jLabel2.setToolTipText("");

        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\SESI_SENAI\\Downloads\\espelhos-esfericos.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 3, 12)); // NOI18N
        jLabel3.setText("Foco =");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 247, -1, -1));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 3, 14)); // NOI18N
        jLabel4.setLabelFor(jLabel1);
        jLabel4.setText("Distância =");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 106, -1, -1));

        campoAlt.setFont(new java.awt.Font("Felix Titling", 3, 14)); // NOI18N
        campoAlt.setText("Altura =");
        campoAlt.setToolTipText("");
        campoAlt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        getContentPane().add(campoAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 178, -1, -1));

        jScrollPane1.setViewportView(campofoco);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 247, 77, -1));

        jScrollPane2.setViewportView(campodist);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 106, 63, 30));

        jScrollPane3.setViewportView(jTextPane3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 178, 67, 23));

        botaolimpar.setBackground(new java.awt.Color(255, 255, 51));
        botaolimpar.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        botaolimpar.setForeground(new java.awt.Color(255, 255, 0));
        botaolimpar.setText("Limpar ");
        botaolimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaolimparActionPerformed(evt);
            }
        });
        getContentPane().add(botaolimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 202, 112, 43));

        botaocalcular.setBackground(new java.awt.Color(255, 255, 51));
        botaocalcular.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        botaocalcular.setForeground(new java.awt.Color(255, 255, 51));
        botaocalcular.setText("Calcular ");
        botaocalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botaocalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 91, -1, 45));

        campotitulo.setFont(new java.awt.Font("Felix Titling", 3, 14)); // NOI18N
        campotitulo.setForeground(new java.awt.Color(255, 255, 0));
        campotitulo.setText("Cálculo De Espelhos Esféricos");
        getContentPane().add(campotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 350, 25));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\SESI_SENAI\\Downloads\\espelhos-esfericos.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -150, 910, 610));

        pack();
    }// </editor-fold>                        

    private void botaocalcularActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void botaolimparActionPerformed(java.awt.event.ActionEvent evt) {                                            
        f = Float.parseFloat(campofoco.getText());
        p = Float.parseFloat(campodist.getText());
         y = Float.parseFloat(campoAlt.getText()); 
         if (f!=0 && p>0 && p!=f && y!=0){
             calculo();
         }
         else{
             if(f==0){
                 campofoco.setText(null);
                 JOptionPane.showMessageDialog(null,"Se o foco for zero \nDigite um novo valor");
                 
             }
             if(f == p){
              
                   JOptionPane.showMessageDialog(null,"O foco não pode ser igual a distância");
             }
             if (p<0){
                 campodist.setText(null);
                 JOptionPane.showMessageDialog(null,"Se a distância for menor que 0\nO objeto estria dentro do espelho");
             }
         if(p==0){
             campodist.setText(null);
             JOptionPane.showMessageDialog(null,"Se a distancia for igual a 0\nO objeto esta ná superficie do espelho por favor digite outro valor"); 
         }
          if(y==0){
             campoAlt.setText(null);
             JOptionPane.showMessageDialog(null,"objeto sem altura, digite um novo valor diferente de 0" );
          }
         }
    }                                           
    public void calculo (){
        float Prf= (f*p)/(f-p);
        float a = (-Prf)/(p);    
        float y1 = a*y;

    
    String resposta = "Trata-se de um espelho esférico";
   resposta = resposta+"Foco:"+f+";\n";
    resposta = resposta+"Distancia entre o objeto e o vértice: "+p+";\n";
    if(f > 0){
        resposta = resposta+"O espelho é côncavo;\n";
    }
    
    else{
        resposta = resposta+"O espelho é cônvexo;\n";
    }
    if(Prf > 0){
        resposta = resposta+" Imagem : real;\n ";
    }
          else{
    resposta = resposta+" Imagem: virtual;\n";
}
          if (a>0){
    resposta = resposta+"Imagem:Direita;\n";
}
          else{
              resposta = resposta+"Imagem:Invertida;\n";
          }
              
              
    resposta=resposta+"imagem é"+a+" vezes o tamanho do objeto;\n";
    resposta =resposta+"A altura da imagem é "+y1+"cm";
    JOptionPane.showMessageDialog(null, resposta);
    }      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(espelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(espelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(espelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(espelhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new espelhos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaocalcular;
    private javax.swing.JButton botaolimpar;
    private javax.swing.JLabel campoAlt;
    private javax.swing.JTextPane campodist;
    private javax.swing.JTextPane campofoco;
    private javax.swing.JLabel campotitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration                   
}
